**Element-wise operations**

In [0]:
import numpy as np

In [3]:
x = np.random.randint(30, size=(2,4))
x

array([[18, 12,  7,  1],
       [18, 17,  4,  5]])

In [4]:
y = np.random.randint(30, size=(2,4))
y

array([[16, 25,  4, 22],
       [19,  8,  3,  9]])

In [5]:
x + y

array([[34, 37, 11, 23],
       [37, 25,  7, 14]])

**Tensor dot**

**Vector Dot**

In [6]:
x = np.random.randint(5, size=(3,))
x

array([0, 3, 4])

In [7]:
y = np.random.randint(5, size=(3,))
y

array([1, 1, 0])

In [8]:
z = np.dot(x,y)
z

3

**Matrix_vector dot**

In [9]:
x = np.random.randint(5, size=(2,3))
x

array([[0, 1, 0],
       [3, 0, 1]])

In [10]:
y = np.random.randint(5, size=(3))
y

array([1, 4, 3])

In [11]:
z = np.dot(x,y)
z

array([4, 6])

In [12]:
z.ndim

1

**Tensor reshaping**

In [13]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [14]:
train_images.shape

(60000, 28, 28)

In [15]:
train_images = train_images.reshape((60000, 28*28))
train_images.shape

(60000, 784)

**Transpose**

In [16]:
x = np.zeros((300,20))
x = np.transpose(x)
print(x.shape)

(20, 300)


In [17]:
x = np.arange(12)
y = x.reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
z = np.transpose(y)
print(z.shape)
z

(4, 3)


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])